[build]
  publish = "dist"
  command = "gulp build"

[[redirects]]
  from = "/news"
  to = "/news/index.html"
  status = 200

[[redirects]]
  from = "https://usemast.com/news/*"
  to = "https://news.usemast.com/:splat"
  status = 302

[[redirects]]
  from = "http://usemast.com/news/*"
  to = "https://news.usemast.com/:splat"
  status = 302
